version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1237:80"
    restart: always
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: data
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./migration/dump.sql:/docker-entrypoint-initdb.d/db_data.sql
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "1218:8080"
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data:
